name: Production Checklist
type: module
description: A checklist for site launch and maintenance based on the active configuration.
# core: 8.x
configure: checklistapi.checklists.production_checklist
package: 'Custom'
dependencies:
  - drupal:checklistapi

# Information added by Drupal.org packaging script on 2018-05-10
version: '8.x-1.0-alpha2'
core: '8.x'
project: 'production_checklist'
datestamp: 1525969988
